name: build
on: [push, pull_request]
jobs:
  demo-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements_locked.txt
      - run: bash tests/test_build.sh
